apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: shipping
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: backend
  template:
    metadata:
      name: shipping
      namespace: roboshop
      labels:
        project: roboshop
        component: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: someshwarsangaraju/shipping:v1
        envFrom:
        - ConfigMapRef:
            name: shipping
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
          intialDelaySeconds: 60
          failureThreshold: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 15
        resources:
          requests:
            cpu: "200m"
            memory: "258Mi"
          limits:
            cpu: "500m"
            memory: "628Mi"

---

apiVersion: autoscaling/v2
#apiVersion: autoscaling/v2beta2  # k8s 1.6+ - scale using the largest of multiple metrics
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  # targetCPUUtilizationPercentage: 70 # multiple metrics using autoscaling/v2beta2 - remove targetCPUUtilizationPercentage if using this
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # - type: Resource
    #   resource:
    #     name: memory
    #     #targetAverageValue: 250M
    #     target:
    #       type: AverageValue
    #       averageValue: 250Mi

